### ISSUE TITLE
Built images do not work

### ISSUE THREAD

**Issue by tmtpune** [NordicPlayground/Nordic-Thingy52-mesh-demo#2]
Hello Rick,

When I use the precompiled images of bridge and node everything works fine, lights can be switched on and off from nrf connect app, lights change color as well. But when i build the images as per your instructions. The led on bridge or node do not breathe. How do i build a single image(softdevice + application) as the precompiled images of yours. I have tried all the posibilities i.e only app, both softdevice and app....but nothing works.  i have built the images using GCC. PLEASE PROVIDE ANY SUGGESTIONS

**Comment by rick1082** [comment]
Hello @tmtpune 

Thanks for your feedback, would it possible for me to know if you met any error or warning during compiling? Are you using Segger Embedded Studio or GCC with Make? Would you please attach the Segger J-Link RTT viewer to the Thingy to see if any error message show up?

**Comment by tmtpune** [comment]
Hi Rick,

I have used GCC with make, and there were no errors while compiling......I have attached the build log(bridge.log) and my Makefile, they may be of some help.

[bridge.log](https://github.com/NordicPlayground/Nordic-Thingy52-mesh-demo/files/1867615/bridge.log)
[Makefile.txt](https://github.com/NordicPlayground/Nordic-Thingy52-mesh-demo/files/1867636/Makefile.txt)

I have used nRFgo Studio to flash the images(softdevice+Application). I even merged both the images into a single image using windows application "mergehex", yet i had no success. No log can be seen on RTT viewer. Please do let me know if you need any more information.


------------------------------------------------------------------------------------


.RAM_START=0x20002b18
RAM_SIZE=0xd4e8 

I did not modify these options in the GCC linker script earlier. Even making these changes did not give the expected result when i compiled using GCC but in the case of SEGGER STUDIO it worked .....What possibly could be the reason??

The application HEX size built by GCC is around 410KB, and the one built by SEGGER STUDIO is around 540KB....What could be the reason for such a difference????

**Comment by rick1082** [comment]
Hello tmtpune,
Sorry for the late reply, I was on business travel. Great that you can use SES to compile and run the demo.
For now we only support SES, haven't support GCC Make. I believe it will need some tweak, I will add GCC Make support in the future, but may not at this time.
