### ISSUE TITLE
Is the demo working with PCA10040?

### ISSUE THREAD

**Issue by pinootto** [NordicPlayground/Nordic-Thingy52-mesh-demo#5]
I have a nRF52-DK with has PCA10040 chip.

I see that the source code is for pca20020_s132.

My question: 
is this source code compatible with PCA10040?

**Comment by rick1082** [comment]
Hello Pinnootto, 
No, the source code is not compatible with PCA10040, because this demo uses some external components like SX1509 IO expander and some sensor which is not on PCA10040.

**Comment by pinootto** [comment]
Hi Rick,

thank you for your clarification.

**Comment by pinootto** [comment]
If I want to develop a similar demo by using the nRF52-DK and nRF52382 chips, is there any project on github which I can use it?

**Comment by rick1082** [comment]
I would like to suggest you check the light switch example in the mesh SDK, because it supports PCA10040 in the default. Or you can remove all the Thingy specific peripheral driver and control logic to fit PCA10040.

**Comment by pinootto** [comment]
OK. Thanks, Rick.
